name: Server builds

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    #This permission is needed to push a release (and/or tags)
    permissions:
      contents: write #nessesary for tag creation and release creation
      actions: write #nessesary for cache deletion
      packages: write #packages write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Publish Ketting
        run: ./gradlew publish
        env:
          KETTINGUSERNAME: ${{ secrets.KETTINGUSERNAME }}
          KETTINGPASSWORD: ${{ secrets.KETTINGPASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build